### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by giganticlab** [barnhill/AndroidOBD#5]
Hi, any documentation how to use this library?

**Comment by barnhill** [comment]
Added some to the readme in this repo.  The bluetooth pairing is not included in this library but once you pair with the bluetooth OBD device (ELM327 only) then you can use the code in the readme to facilitate getting pids from it.

**Comment by barnhill** [comment]
Readme updated here https://github.com/barnhill/AndroidOBD/commit/f2209b693405d7c108639fdeee29712b2a6910b9
